name: Update README Activity
on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  recent-activity:
    name: 'Update README with latest activity'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/Checkout@v3
      - name: 'Update README.md with recent activity'
        uses: romangrewal/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.recent_activity }}
