name: Update README Activity
on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  update_activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checks out your repository
      - name: Update README
        uses: readme-workflows/recent-activity@main # Uses the Readme-Workflows/recent-activity action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          GH_USERNAME: ${{ secrets.GITHUB_USERNAME }}
#          CONFIG_FILE: 'path/to/your/config.json'
          # Add your customization settings here, e.g.:
          # disable_events: "PullRequestEvent,IssuesEvent"
          # commit_message: "Updated activity in README"
          # timezone: "America/New_York"
          # commit_username: "MyBot"
          # commit_email: "mybot@example.com"
